### ISSUE TITLE
Version 2.3.1 raising error when using connectionString: $([Variable Name])

### ISSUE THREAD

**Issue by mauriciomagni** [cmeeren/Facil#38] opened 2022-03-02 11:58 UTC
After updating to version 2.3.1, it started raising an error when trying to generate DbGen file, saying:
facil.yaml(0 , 0) : error : The variable $(Db) could not be found in the specified configuration sources

Going back to version 2.3.0 works as expected.

In my facil.yaml file I have this configuration:
```
rulesets:
  - connectionString: $(Db)
```

**Comment by cmeeren** [comment] 2022-03-02 12:25
I can't reproduce. The following works fine in Facil's test project:

```yaml
configs:
  - appSettings: appsettings.json

rulesets:
  - connectionString: $(connectionString)
```

I need a minimal repro. Could you create one?

**Comment by cmeeren** [comment] 2022-03-02 12:28
Also, please verify that the variable casing is correct.

**Comment by mauriciomagni** [comment] 2022-03-03 09:41
hello Cmeeren
The casing is correct, and we have been using it until this new version.
I will create a small project to try to reproduce this error.
Something I did not mentioned before is the "configs:" configuration:
`configs:
  - envVars: MyApp__
`
I will get back to you with minimal repro.
Kind regards,
Mauricio

**Comment by mauriciomagni** [comment] 2022-03-03 09:53
[Facil231.zip](https://github.com/cmeeren/Facil/files/8176748/Facil231.zip)
Dear Cmeeren
Attached is the minimal repro.
Here is how I have configure the environment variable:
![image](https://user-images.githubusercontent.com/20417121/156540452-1852015d-41c6-4dc4-b2ac-3815afcd164f.png)
Hope this help.
If you cannot look at it, I will try to create a pull request during the weekend.
Regards,
Mauricio

**Comment by cmeeren** [comment] 2022-03-03 11:34
Thanks, I'll have a look at it. If you happen to know where the bug is, don't hesitate to let me know.

**Comment by cmeeren** [comment] 2022-03-03 12:23
Related to https://github.com/dotnet/runtime/issues/65756

I'll downgrade if there's no new fix published.

**Comment by cmeeren** [comment] 2022-03-03 12:42
Fixed in v/2.3.2.

**Closed by cmeeren** 2022-03-03 12:42 UTC
